feat: open telemetry tracing
filecoin-saturn/caboose pull request #87
Opened 2023-04-12 09:22 UTC by hacdias

Adds Open Telemetry tracing spans. Context: https://github.com/ipfs/bifrost-gateway/issues/68#issuecomment-1504921191.

This is not necessarily required. On the screenshot below you see the tracing result from the Bifrost Gateway up until the HTTP request Caboose makes to the Saturn node. What this PR adds is the `Caboose.*` trace spans. The HTTP GET already worked.

![Screenshot 2023-04-12 at 11 19 18](https://user-images.githubusercontent.com/5447088/231413770-1258a7d8-1e87-454c-8b0c-e53768b1cc5c.png)

@lidel @willscott not sure where is the most value to put the spans here, but this seems like a good start. Feel free to add/remove some.

2023-04-24 15:06 UTC, lidel requested changes
We should  remove `Blockstore.` prefix, at least for `Fetch`, which  is an Exchange interface, and not Blockstore one.

2023-04-25 22:20 UTC, lidel approved these changes

2023-04-25 22:21 UTC, lidel approved these changes
lgtm, should be good enough for now 
@willscott  / @aarshkshah1992  ok to merge? we can add more spans in the future, if needed

2023-04-26 07:02 UTC, willscott approved these changes

2023-04-26 07:03 UTC, merged